version: "3.9"
volumes:
  db-store:
services:
  db:
    image: mysql:8.0.28
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-local}
      - MYSQL_USER=${DB_USER:-test_user}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}